[package]
name = "bst_iterator"
version = "0.1.0"
authors = ["uhanson <uhanson@perlovka.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
